### ISSUE TITLE
Request instructions on how to use -query-predicate

### ISSUE THREAD

**Issue by RAbraham** [thomasrebele/bashlog#2]
Hi,
I'm new to Datalog so I have a newbie question.
My locals.datalog file is(your first example):
```bash
facts(_, S, P, O) :~ cat *.tsv
main(X) :- 
   facts(_, X, "<wasBornIn>", Y),
   facts(_, X, "<diedIn>", Y).
```
I'm not sure how to use the -query-predicate option. Can you give me an example on what value to give there?

```bash
java -jar bashlog-datalog.jar --query-file locals.datalog  -query-predicate  __what_do_I_put_here  > query1.sh
```

**Comment by thomasrebele** [comment]
Hello,
thanks for the question! It made me discover that the example in the Readme had some mistakes. I fixed them. The `<predicate>` specifies the datalog predicate that should be evaluated.
In the example it you could use `main`, `main/1`, `facts`, or `facts/4`.
The correct call would be `java -jar bashlog-datalog.jar --query-file locals.datalog --query-pred main`.

**Comment by RAbraham** [comment]
Great, Thanks!
