### ISSUE TITLE
Introducing facts

### ISSUE THREAD

**Issue by RAbraham** [thomasrebele/bashlog#3]
This may be my lack of Datalog skills but the program I wrote was:

```bash
type("Pop", "Rajiv", "father").
type("Sajan", "Anisha", "father").
type("Rajiv", "Aks", "father").

father(X, Y) :- type(X, Y, "father").
grandfather(X, Y) :- father(X, Z), father(Z, Y).
main(X) :- grandfather(X).

```

When I run the generated bash script, I was expecting to see 
```
Pop Aks
```

However, I don't see any result. What am I doing wrong?

**Comment by RAbraham** [comment]
Also, is `type` a special keyword like `main`?  Could I write
```bash
father("Pop", "Rajiv").
father("Sajan", "Anisha").
father("Rajiv", "Aks").

grandfather(X, Y) :- father(X, Z), father(Z, Y).
main(X) :- grandfather(X).
```
This didn't work either

**Comment by RAbraham** [comment]
The example on the page worked for me though i.e.

```bash
type("albert", "person").
type("marie", "person").
people(X) :- type(X, "person").
```

**Comment by RAbraham** [comment]
I tried without the main clause and also 
```bash
type("Pop", "Rajiv", "father").
type("Sajan", "Anisha", "father").
type("Rajiv", "Aks", "father").

father(X, Y) :- type(X, Y, "father").
grandfather(X, Y) :- father(X, Z),  type(Z, Y, "father").
```

but the script hangs

**Comment by thomasrebele** [comment]
Hello,
you could either query the grandfather relation directly:
```
java -jar bashlog-datalog.jar --query-file locals.datalog --query-pred grandfather/2
```
or you could change the last line to 
```
main(X, Y) :- grandfather(X, Y).
```

Your example had `main(X) :- grandfather(X).`, which would query the non-existing relation grandfather/**1**. But only the relation grandfather/**2** is defined.

Your last example prints `Pop	Aks` if I generate the script with the parameter `--query-pred grandfather/2`. Could you check again if it hangs? If that's the case, could you please upload the generated script and how you call it?

**Comment by RAbraham** [comment]
:(. Working late at night shows. 
I'm using your online page and not the `jar` yet.
I played with it again and I still had it hang multiple times. But interestingly, it worked once! It's the same program but I think the reason may be that the facts are printed in the bash script in different order?

```bash
type("Pop", "Rajiv", "father").
type("Sajan", "Anisha", "father").
type("Rajiv", "Aks", "father").

father(X, Y) :- type(X, Y, "father").
grandfather(X, Y) :- father(X, Z), father(Z, Y).
main(X, Y) :- grandfather(X, Y).
```
Generated Output:
```bash
#!/bin/bash
###############################################################
# This script was generated by bashlog
# For more information, visit thomasrebele.org/projects/bashlog
###############################################################

export LC_ALL=C
mkdir -p tmp
rm -f tmp/*
if type mawk > /dev/null; then awk="mawk"; else awk="awk"; fi
sort="sort "
check() { grep -- $1 <(sort --help) > /dev/null; }
check "--buffer-size" && sort="$sort --buffer-size=50% "
check "--parallel"    && sort="$sort --parallel=2 "

read_ntriples() { $awk -F" " '{ sub(" ", "\t"); sub(" ", "\t"); sub(/ \.$/, ""); print $0 }' "$@"; }
conv_ntriples() { $awk -F$'\t' '{ print $1 " " $2 " " $3 " ." }'; }



mkfifo tmp/lock_mat0; ( $awk -v FS=$'\t' ' 
      BEGIN { 
       out0c1_cond2["father"] = "1"; 
      }
    
     (($3) in out0c1_cond2){ print $1 FS $2 } 
      ' \
    <(cat  <<EOF
Pop	Rajiv	father
Rajiv	Aks	father
Sajan	Anisha	father
EOF
        ) > tmp/mat0; mv tmp/lock_mat0 tmp/done_mat0; cat tmp/done_mat0 > /dev/null & exec 3> tmp/done_mat0; exec 3>&-; ) & 

# plan
$sort -t $'\t' -k 1 -k 2 -u \
<(join -t $'\t' -1 2 -2 1 -o 1.1,2.2 \
    <(cat tmp/lock_mat0 1>&2 2>/dev/null ;  \
        $sort -t $'\t' -k 2 tmp/mat0) \
    <(cat tmp/lock_mat0 1>&2 2>/dev/null ;  \
        $sort -t $'\t' -k 1 tmp/mat0))

 rm -f tmp/*

```


If you want to reproduce it, on the site, paste the above datalog program, and run the output. If it still works for you, do you mind, generating again :). I got it to work once in 10 times so far.


Side Note: if I do `main(X) :- grandfather(X, Y)` or `main(Y) :- grandfather(X, Y)`, it works but not always when I use `main(X, Y)`

**Comment by thomasrebele** [comment]
Maybe our synchronization technique does not work for your operating system. Could you tell me which OS you use? Which version of bash?

On August 13, 2019 3:31:05 AM GMT+02:00, Rajiv Abraham <notifications@github.com> wrote:
>:(. Working late at night shows. 
>I'm using your online page and not the `jar` yet.
>I played with it again and I still had it hang multiple times. But
>interestingly, it worked once! It's the same program but I think the
>reason may be that the facts are printed in the bash script in
>different order?
>
>```bash
>type("Pop", "Rajiv", "father").
>type("Sajan", "Anisha", "father").
>type("Rajiv", "Aks", "father").
>
>father(X, Y) :- type(X, Y, "father").
>grandfather(X, Y) :- father(X, Z), father(Z, Y).
>main(X, Y) :- grandfather(X, Y).
>```
>Generated Output:
>```bash
>#!/bin/bash
>###############################################################
># This script was generated by bashlog
># For more information, visit thomasrebele.org/projects/bashlog
>###############################################################
>
>export LC_ALL=C
>mkdir -p tmp
>rm -f tmp/*
>if type mawk > /dev/null; then awk="mawk"; else awk="awk"; fi
>sort="sort "
>check() { grep -- $1 <(sort --help) > /dev/null; }
>check "--buffer-size" && sort="$sort --buffer-size=50% "
>check "--parallel"    && sort="$sort --parallel=2 "
>
>read_ntriples() { $awk -F" " '{ sub(" ", "\t"); sub(" ", "\t"); sub(/
>\.$/, ""); print $0 }' "$@"; }
>conv_ntriples() { $awk -F$'\t' '{ print $1 " " $2 " " $3 " ." }'; }
>
>
>
>mkfifo tmp/lock_mat0; ( $awk -v FS=$'\t' ' 
>      BEGIN { 
>       out0c1_cond2["father"] = "1"; 
>      }
>    
>     (($3) in out0c1_cond2){ print $1 FS $2 } 
>      ' \
>    <(cat  <<EOF
>Pop	Rajiv	father
>Rajiv	Aks	father
>Sajan	Anisha	father
>EOF
>) > tmp/mat0; mv tmp/lock_mat0 tmp/done_mat0; cat tmp/done_mat0 >
>/dev/null & exec 3> tmp/done_mat0; exec 3>&-; ) & 
>
># plan
>$sort -t $'\t' -k 1 -k 2 -u \
><(join -t $'\t' -1 2 -2 1 -o 1.1,2.2 \
>    <(cat tmp/lock_mat0 1>&2 2>/dev/null ;  \
>        $sort -t $'\t' -k 2 tmp/mat0) \
>    <(cat tmp/lock_mat0 1>&2 2>/dev/null ;  \
>        $sort -t $'\t' -k 1 tmp/mat0))
>
> rm -f tmp/*
>
>```
>
>
>If you want to reproduce it, on the site, paste the above datalog
>program, and run the output. If it still works for you, do you mind,
>generating again :). I got it to work once in 10 times so far.
>
>
>Side Note: if I do `main(X) :- grandfather(X, Y)` or `main(Y) :-
>grandfather(X, Y)`, it works but not always when I use `main(X, Y)`
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/thomasrebele/bashlog/issues/3#issuecomment-520653828

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by RAbraham** [comment]
I'm on MacOS(Mojave 10.14.6). I was on a default version of `bash` but I updated it but I still have the same issue :) though with more success.
```bash
bash --version
GNU bash, version 5.0.7(1)-release (x86_64-apple-darwin18.5.0)
```
A program which works intermittently(I can't yet reproduce the hanging with surety)
```bash
#!/bin/bash
###############################################################
# This script was generated by bashlog
# For more information, visit thomasrebele.org/projects/bashlog
###############################################################

export LC_ALL=C
mkdir -p tmp
rm -f tmp/*
if type mawk > /dev/null; then awk="mawk"; else awk="awk"; fi
sort="sort "
check() { grep -- $1 <(sort --help) > /dev/null; }
check "--buffer-size" && sort="$sort --buffer-size=50% "
check "--parallel"    && sort="$sort --parallel=2 "

read_ntriples() { $awk -F" " '{ sub(" ", "\t"); sub(" ", "\t"); sub(/ \.$/, ""); print $0 }' "$@"; }
conv_ntriples() { $awk -F$'\t' '{ print $1 " " $2 " " $3 " ." }'; }


mkfifo tmp/lock_mat0; ( $awk -v FS=$'\t' ' 
      BEGIN { 
       out0c1_cond2["father"] = "1"; 
      }
    
     (($3) in out0c1_cond2){ print $1 FS $2 } 
      ' \
    <(cat  <<EOF
Sajan	Anisha	father
Rajiv	Aks	father
Pop	Rajiv	father
EOF
        ) > tmp/mat0; mv tmp/lock_mat0 tmp/done_mat0; cat tmp/done_mat0 > /dev/null & exec 3> tmp/done_mat0; exec 3>&-; ) & 

# plan
$sort -t $'\t' -k 1 -k 2 -u \
<(join -t $'\t' -1 2 -2 1 -o 1.1,2.2 \
    <(cat tmp/lock_mat0 1>&2 2>/dev/null ;  \
        $sort -t $'\t' -k 2 tmp/mat0) \
    <(cat tmp/lock_mat0 1>&2 2>/dev/null ;  \
        $sort -t $'\t' -k 1 tmp/mat0))

 rm -f tmp/*
```

**Comment by thomasrebele** [comment]
Unfortunately I don't have a Mac available for testing. Could you execute the following script and post the output? That way we can find out at least at which moment the script hangs.

```
#!/bin/bash

echo "before creating FIFO" 1>&2
mkfifo tmp/lock_mat0; 
echo "after creating FIFO" 1>&2
( 
	echo "before fact input" 1>&2
cat  <<EOF
Rajiv	Aks	father
EOF
    > tmp/mat0; 
	echo "after fact input" 1>&2
	mv tmp/lock_mat0 tmp/done_mat0; 
	echo "sync step 1" 1>&2
	cat tmp/done_mat0 > /dev/null &
	echo "sync step 2" 1>&2
	exec 3> tmp/done_mat0; 
	echo "sync step 3" 1>&2
	exec 3>&-; 
	echo "sync step 4" 1>&2
) & 

# plan
echo "before lock" 1>&2
cat tmp/lock_mat0 1>&2 2>/dev/null
echo "after lock" 1>&2

cat tmp/mat0

echo "after main plan" 1>&2
```

**Comment by RAbraham** [comment]
Here you go:

```bash
before creating FIFO
after creating FIFO
before lock
before fact input
Rajiv	Aks	father
after fact input
sync step 1
sync step 2
sync step 3
sync step 4
after lock
after main plan
```

**Comment by thomasrebele** [comment]
Ah, sorry, my instructions were not precise enough. Could you execute the script until it hangs? Maybe with something like `for ((i=0; i<1000; i++)); do echo "---"; bash query.sh; done`, and post the output starting from the last `---`.

**Comment by RAbraham** [comment]
np at all, here you go. I'm posting the output of the last few iterations because something starts happening before.

```bash
---
before creating FIFO
after creating FIFO
before lock
before fact input
ancester.sh: fork: retry: Resource temporarily unavailable
ancester.sh: fork: retry: Resource temporarily unavailable
ancester.sh: fork: retry: Resource temporarily unavailable
Rajiv	Aks	father
after fact input
sync step 1
sync step 2
sync step 3
sync step 4
after lock
after main plan
---
before creating FIFO
after creating FIFO
before fact input
before lock
ancester.sh: fork: retry: Resource temporarily unavailable
Rajiv	Aks	father
after fact input
sync step 1
sync step 2
sync step 3
sync step 4
ancester.sh: fork: Interrupted system call
---
before creating FIFO
after creating FIFO
before lock
before fact input
ancester.sh: fork: retry: Resource temporarily unavailable
Rajiv	Aks	father
after fact input
sync step 1
sync step 2
sync step 3
sync step 4
after lock
after main plan
---
before creating FIFO
after creating FIFO
before lock
before fact input
ancester.sh: fork: retry: Resource temporarily unavailable
ancester.sh: fork: retry: Resource temporarily unavailable
ancester.sh: fork: retry: Resource temporarily unavailable
ancester.sh: fork: retry: Resource temporarily unavailable
ancester.sh: fork: Resource temporarily unavailable

```

**Comment by RAbraham** [comment]
I'm curious, if you run the above script on a non Mac machine(1000 iterations), does it run successfully always?

**Comment by thomasrebele** [comment]
Yes, I tried it several times, and it always prints 1000 times "Pop Aks" after about 21s runtime.
Maybe the problem is related to the `fork: retry: Resource temporarily unavailable` messages.
Could you try to increase the number of allowed processes as described [here](http://blog.ghostinthemachines.com/2010/01/19/mac-os-x-fork-resource-temporarily-unavailable/)?

**Comment by RAbraham** [comment]
@thomasrebele  Thank you so much for the resource! I followed that and another. It runs the first time. But hangs on the second run. I have to play with my settings but I think the issue is resolved from an understanding perspective.

**Comment by RAbraham** [comment]
I just reopened the issue because a question sprung up. Now, the for loop above always works for the first complete execution of the script. It begins to fail on the second execution of the script.

I make an assumption that when the script is executed and finishes the first time, all the child processes spawned by the script generated by bashlog will be closed too? If so, then the second execution of the script should be fine? I'm sure I'm lacking in knowledge here and am glad for any of your views.

**Comment by thomasrebele** [comment]
Seems that we make some progress. Yes, all child processes should finish and release their resources once they have completed their task. After the execution of the script, all resources should be released again. My co-authors had both macs, but they haven't encountered such problems as far as I can remember. Maybe some constraints were introduced in the macOS since then.

Which execution hangs the second time? The script `query.sh`, or the loop that run the script 1000 times? Does it still print `Resource temporarily unavailable` warnings? Could you post the last blocks of the output when it hangs?

**Comment by RAbraham** [comment]
My Mac is from 2013. Maybe that's the issue? :) Here is the output of the second run(after the first completed):
```
---
before creating FIFO
after creating FIFO
before lock
before fact input
ancestor.sh: fork: retry: Resource temporarily unavailable
Rajiv Aks father
after fact input
sync step 1
sync step 2
sync step 3
sync step 4
after lock
after main plan
---
before creating FIFO
after creating FIFO
before lock
before fact input
ancestor.sh: fork: retry: Resource temporarily unavailable
ancestor.sh: fork: retry: Resource temporarily unavailable
ancestor.sh: fork: retry: Resource temporarily unavailable
ancestor.sh: fork: retry: Resource temporarily unavailable
ancestor.sh: fork: Resource temporarily unavailable
```

**Comment by thomasrebele** [comment]
Normally the age of the computer shouldn't play a role here :) What are the current limits for the number of processes? (`sysctl -a | grep maxproc`)?

**Comment by RAbraham** [comment]
haha, here it is:
```
➜  ~ sysctl -a | grep maxproc
kern.maxproc: 2128
kern.maxprocperuid: 3072
```

**Comment by thomasrebele** [comment]
Could you try to set it to a bigger value, such as 32768? That's the value of my system for `cat /proc/sys/kernel/pid_max`

**Comment by RAbraham** [comment]
I can't change it more than `2500` :(. I was wondering if my original question is still valid. If the child processes are closed after every run and it runs successfully the first time, then we should still have the current processes number less than the max limit and hence it should run successfully a second time? 

regarding max process limit,  I'll try to figure that out more on my end.  Thank you so much for your support! I appreciate it.

**Comment by RAbraham** [comment]
So, I just learned that it's hardcoded to 2500. https://apple.stackexchange.com/questions/368011/how-to-increase-the-max-user-processes-hard-limitmojave.

I was atleast able to run it the second time without a block. It's now failing on the third run :). So that's progress!

**Comment by RAbraham** [comment]
Hi,
on the question above, @lx07 made an interesting comment.

"from comments on github there seems some confusion between maxproc (max number of concurrent processes) and pid_max (where process id number wraps). maxproc is 2500 while pid_max is 99999 on macOS. On linux pid_max is 32768 for 32 bit systems or up to 4194304 for 64 bit. Looks like (as you suggested) perhaps something isn't closing properly as you shouldn't need that many active processes. – lx07 2 hours ago "


I think I can't change my pid_max(https://stackoverflow.com/questions/44533802/maximum-pid-on-osx). What is the `maxproc` number on your system?

**Comment by thomasrebele** [comment]
So it seems the problem is somehow related to the maximum number of processes. I found those limits on my system:

```
$ cat /proc/sys/kernel/pid_max
32768
$ ulimit -a
...
-u: processes                       31089
-n: file descriptors                1024
...
-x: file locks                      unlimited
...
```

There might be a problem with the query script: when I execute it, it increases the total number of processes by one. There might be one process that doesn't close correctly. I'll investigate.

**Comment by thomasrebele** [comment]
Indeed, there was a race condition: if the command `cat tmp/done_mat0 > /dev/null &` started after `exec 3>&-` has been executed, then it would wait on the named pipe `tmp/done_mat0` forever. I found a workaround. Could you check whether the following script runs without hanging? The number of processes (before and after) should stay the same, i.e., not increase by one after every run. If it works as expected then I can fix it in the code generation.

```
#!/bin/bash

echo "processes (before): $(ps -e | wc -l)" 1>&2

unlock() {
	mv "$1" "$2"; 
	(
		cat "$2" > /dev/null
		rm "$2"
	) &
	while [ -p "$2" ]; do
		exec 3> "$2";
		exec 3>&-; 
	done
}

mkfifo tmp/lock_mat0; 
( 
cat  <<EOF
Rajiv	Aks	father
EOF
	> tmp/mat0; 
	unlock tmp/lock_mat0 tmp/done_mat0
) & 

# plan
cat tmp/lock_mat0 1>&2 2>/dev/null

cat tmp/mat0

echo "processes (after): $(ps -e | wc -l)" 1>&2
```

**Comment by RAbraham** [comment]
I'm happy that we are moving forward!
here it is:
```
processes (before):      390
mkfifo: tmp/lock_mat0: File exists
Rajiv	Aks	father
processes (after):      391
```

**Comment by thomasrebele** [comment]
Normally the number of processes should have stayed 390. Could you do the following steps?
1. Delete the files in the tmp folder where you run the script
2. Run the following command (replacing query3.sh with the name of the new script)
```bash -c 'for ((i=1; i<1000; i++)); do bash ./query3.sh | sed "s/^/$i: /"; done'```
3. Post the first ten lines and last ten lines

**Comment by RAbraham** [comment]
Is this what you were looking for
```bash
processes (before):      379
mkfifo: tmp/lock_mat0: No such file or directory
./ancestor.sh: line 22: tmp/mat0: No such file or directory
cat: tmp/mat0: No such file or directory
mv: rename tmp/lock_mat0 to tmp/done_mat0: No such file or directory
cat: tmp/done_mat0: No such file or directory
rm: tmp/done_mat0: No such file or directory
processes (after):      380
1: Rajiv	Aks	father
processes (before):      379
mkfifo: tmp/lock_mat0: No such file or directory
cat: tmp/mat0: No such file or directory
./ancestor.sh: line 22: tmp/mat0: No such file or directory
mv: rename tmp/lock_mat0 to tmp/done_mat0: No such file or directory
cat: tmp/done_mat0: No such file or directory
rm: tmp/done_mat0: No such file or directory
processes (after):      381
2: Rajiv	Aks	father
processes (before):      380
mkfifo: tmp/lock_mat0: No such file or directory
./ancestor.sh: line 22: tmp/mat0: No such file or directory
cat: tmp/mat0: No such file or directory
mv: rename tmp/lock_mat0 to tmp/done_mat0: No such file or directory
cat: tmp/done_mat0: No such file or directory
rm: tmp/done_mat0: No such file or directory
processes (after):      381
3: Rajiv	Aks	father
processes (before):      380
mkfifo: tmp/lock_mat0: No such file or directory
./ancestor.sh: line 22: tmp/mat0: No such file or directory
cat: tmp/mat0: No such file or directory
mv: rename tmp/lock_mat0 to tmp/done_mat0: No such file or directory
cat: tmp/done_mat0: No such file or directory
rm: tmp/done_mat0: No such file or directory
processes (after):      382
4: Rajiv	Aks	father
------

processes (before):      377
mkfifo: tmp/lock_mat0: No such file or directory
cat: tmp/mat0: No such file or directory
./ancestor.sh: line 22: tmp/mat0: No such file or directory
mv: rename tmp/lock_mat0 to tmp/done_mat0: No such file or directory
cat: tmp/done_mat0: No such file or directory
rm: tmp/done_mat0: No such file or directory
processes (after):      379
996: Rajiv	Aks	father
processes (before):      377
mkfifo: tmp/lock_mat0: No such file or directory
cat: tmp/mat0: No such file or directory
./ancestor.sh: line 22: tmp/mat0: No such file or directory
mv: rename tmp/lock_mat0 to tmp/done_mat0: No such file or directory
cat: tmp/done_mat0: No such file or directory
rm: tmp/done_mat0: No such file or directory
processes (after):      379
997: Rajiv	Aks	father
processes (before):      377
mkfifo: tmp/lock_mat0: No such file or directory
./ancestor.sh: line 22: tmp/mat0: No such file or directory
cat: tmp/mat0: No such file or directory
mv: rename tmp/lock_mat0 to tmp/done_mat0: No such file or directory
cat: tmp/done_mat0: No such file or directory
rm: tmp/done_mat0: No such file or directory
processes (after):      379
998: Rajiv	Aks	father
processes (before):      377
mkfifo: tmp/lock_mat0: No such file or directory
cat: tmp/mat0: No such file or directory
./ancestor.sh: line 22: tmp/mat0: No such file or directory
mv: rename tmp/lock_mat0 to tmp/done_mat0: No such file or directory
cat: tmp/done_mat0: No such file or directory
rm: tmp/done_mat0: No such file or directory
processes (after):      379
999: Rajiv	Aks	father
```

**Comment by RAbraham** [comment]
I'm guessing that when this runs on your laptop, then the number of processes remain the same?

**Comment by RAbraham** [comment]
out of curiosity, I ran this on an ubuntu docker image. Here is the output
```bash
rocesses (before): 8
mkfifo: cannot create fifo 'tmp/lock_mat0': No such file or directory
./ancestor.sh: line 22: tmp/mat0: No such file or directory
cat: tmp/mat0: No such file or directory
mv: cannot stat 'tmp/lock_mat0': No such file or directory
cat: tmp/done_mat0: No such file or directory
rm: cannot remove 'tmp/done_mat0': No such file or directory
processes (after): 8
1: Rajiv        Aks     father
processes (before): 8
mkfifo: cannot create fifo 'tmp/lock_mat0': No such file or directory
./ancestor.sh: line 22: tmp/mat0: No such file or directory
cat: tmp/mat0: No such file or directory
mv: cannot stat 'tmp/lock_mat0': No such file or directory
cat: processes (after): 10
tmp/done_mat0: No such file or directory
rm: cannot remove 'tmp/done_mat0': No such file or directory
2: Rajiv        Aks     father
processes (before): 8
mkfifo: cannot create fifo 'tmp/lock_mat0': No such file or directory
./ancestor.sh: line 22: tmp/mat0: No such file or directory
cat: tmp/mat0: No such file or directory
mv: cannot stat 'tmp/lock_mat0': No such file or directory
cat: tmp/done_mat0: No such file or directory
rm: cannot remove 'tmp/done_mat0': No such file or directory
processes (after): 9
3: Rajiv        Aks     father
processes (before): 8
mkfifo: cannot create fifo 'tmp/lock_mat0': No such file or directory
./ancestor.sh: line 22: tmp/mat0: No such file or directory
cat: tmp/mat0: No such file or directory
mv: cannot stat 'tmp/lock_mat0': No such file or directory
cat: tmp/done_mat0: No such file or directory
rm: cannot remove 'tmp/done_mat0': No such file or directory
processes (after): 9
4: Rajiv        Aks     father
...................
processes (before): 8
mkfifo: cannot create fifo 'tmp/lock_mat0': No such file or directory
./ancestor.sh: line 22: tmp/mat0: No such file or directory
cat: tmp/mat0: No such file or directory
mv: cannot stat 'tmp/lock_mat0': No such file or directory
cat: tmp/done_mat0: No such file or directory
rm: cannot remove 'tmp/done_mat0': No such file or directory
processes (after): 8
996: Rajiv      Aks     father
processes (before): 8
mkfifo: cannot create fifo 'tmp/lock_mat0': No such file or directory
./ancestor.sh: line 22: tmp/mat0: No such file or directory
cat: tmp/mat0: No such file or directory
mv: cannot stat 'tmp/lock_mat0': No such file or directory
cat: tmp/done_mat0: No such file or directory
rm: cannot remove 'tmp/done_mat0': No such file or directory
processes (after): 8
997: Rajiv      Aks     father
processes (before): 8
mkfifo: cannot create fifo 'tmp/lock_mat0': No such file or directory
./ancestor.sh: line 22: tmp/mat0: No such file or directory
cat: tmp/mat0: No such file or directory
mv: cannot stat 'tmp/lock_mat0': No such file or directory
cat: tmp/done_mat0: No such file or directory
rm: cannot remove 'tmp/done_mat0': No such file or directory
processes (after): 9
998: Rajiv      Aks     father
processes (before): 8
mkfifo: cannot create fifo 'tmp/lock_mat0': No such file or directory
./ancestor.sh: line 22: tmp/mat0: No such file or directory
cat: tmp/mat0: No such file or directory
mv: cannot stat 'tmp/lock_mat0': No such file or directory
cat: tmp/done_mat0: No such file or directory
rm: cannot remove 'tmp/done_mat0': No such file or directory
processes (after): 10
999: Rajiv      Aks     father
```

**Comment by thomasrebele** [comment]
Ah, sorry, the script doesn't recreate the tmp folder. Could you create it with mkdir tmp before running the script?

On September 2, 2019 6:05:01 PM GMT+02:00, Rajiv Abraham <notifications@github.com> wrote:
>out of curiosity, I ran this on an ubuntu docker image. Here is the
>output
>```bash
>rocesses (before): 8
>mkfifo: cannot create fifo 'tmp/lock_mat0': No such file or directory
>./ancestor.sh: line 22: tmp/mat0: No such file or directory
>cat: tmp/mat0: No such file or directory
>mv: cannot stat 'tmp/lock_mat0': No such file or directory
>cat: tmp/done_mat0: No such file or directory
>rm: cannot remove 'tmp/done_mat0': No such file or directory
>processes (after): 8
>1: Rajiv        Aks     father
>processes (before): 8
>mkfifo: cannot create fifo 'tmp/lock_mat0': No such file or directory
>./ancestor.sh: line 22: tmp/mat0: No such file or directory
>cat: tmp/mat0: No such file or directory
>mv: cannot stat 'tmp/lock_mat0': No such file or directory
>cat: processes (after): 10
>tmp/done_mat0: No such file or directory
>rm: cannot remove 'tmp/done_mat0': No such file or directory
>2: Rajiv        Aks     father
>processes (before): 8
>mkfifo: cannot create fifo 'tmp/lock_mat0': No such file or directory
>./ancestor.sh: line 22: tmp/mat0: No such file or directory
>cat: tmp/mat0: No such file or directory
>mv: cannot stat 'tmp/lock_mat0': No such file or directory
>cat: tmp/done_mat0: No such file or directory
>rm: cannot remove 'tmp/done_mat0': No such file or directory
>processes (after): 9
>3: Rajiv        Aks     father
>processes (before): 8
>mkfifo: cannot create fifo 'tmp/lock_mat0': No such file or directory
>./ancestor.sh: line 22: tmp/mat0: No such file or directory
>cat: tmp/mat0: No such file or directory
>mv: cannot stat 'tmp/lock_mat0': No such file or directory
>cat: tmp/done_mat0: No such file or directory
>rm: cannot remove 'tmp/done_mat0': No such file or directory
>processes (after): 9
>4: Rajiv        Aks     father
>...................
>processes (before): 8
>mkfifo: cannot create fifo 'tmp/lock_mat0': No such file or directory
>./ancestor.sh: line 22: tmp/mat0: No such file or directory
>cat: tmp/mat0: No such file or directory
>mv: cannot stat 'tmp/lock_mat0': No such file or directory
>cat: tmp/done_mat0: No such file or directory
>rm: cannot remove 'tmp/done_mat0': No such file or directory
>processes (after): 8
>996: Rajiv      Aks     father
>processes (before): 8
>mkfifo: cannot create fifo 'tmp/lock_mat0': No such file or directory
>./ancestor.sh: line 22: tmp/mat0: No such file or directory
>cat: tmp/mat0: No such file or directory
>mv: cannot stat 'tmp/lock_mat0': No such file or directory
>cat: tmp/done_mat0: No such file or directory
>rm: cannot remove 'tmp/done_mat0': No such file or directory
>processes (after): 8
>997: Rajiv      Aks     father
>processes (before): 8
>mkfifo: cannot create fifo 'tmp/lock_mat0': No such file or directory
>./ancestor.sh: line 22: tmp/mat0: No such file or directory
>cat: tmp/mat0: No such file or directory
>mv: cannot stat 'tmp/lock_mat0': No such file or directory
>cat: tmp/done_mat0: No such file or directory
>rm: cannot remove 'tmp/done_mat0': No such file or directory
>processes (after): 9
>998: Rajiv      Aks     father
>processes (before): 8
>mkfifo: cannot create fifo 'tmp/lock_mat0': No such file or directory
>./ancestor.sh: line 22: tmp/mat0: No such file or directory
>cat: tmp/mat0: No such file or directory
>mv: cannot stat 'tmp/lock_mat0': No such file or directory
>cat: tmp/done_mat0: No such file or directory
>rm: cannot remove 'tmp/done_mat0': No such file or directory
>processes (after): 10
>999: Rajiv      Aks     father
>```
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/thomasrebele/bashlog/issues/3#issuecomment-527194545

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by RAbraham** [comment]
Here you go:
```bash
processes (before):      298
processes (after):      298
1: Rajiv	Aks	father
processes (before):      298
processes (after):      298
2: Rajiv	Aks	father
processes (before):      298
processes (after):      298
3: Rajiv	Aks	father
processes (before):      298
processes (after):      298
4: Rajiv	Aks	father
processes (before):      298
processes (after):      298
5: Rajiv	Aks	father
processes (before):      298
processes (after):      298
6: Rajiv	Aks	father
processes (before):      298
processes (after):      298
7: Rajiv	Aks	father
processes (before):      298
processes (after):      298
8: Rajiv	Aks	father
processes (before):      298
processes (after):      298
9: Rajiv	Aks	father
processes (before):      298
processes (after):      298
10: Rajiv	Aks	father
processes (before):      298
processes (after):      298
11: Rajiv	Aks	father
--- 

processes (before):      298
processes (after):      298
989: Rajiv	Aks	father
processes (before):      298
processes (after):      298
990: Rajiv	Aks	father
processes (before):      298
processes (after):      298
991: Rajiv	Aks	father
processes (before):      298
processes (after):      298
992: Rajiv	Aks	father
processes (before):      298
processes (after):      298
993: Rajiv	Aks	father
processes (before):      298
processes (after):      298
994: Rajiv	Aks	father
processes (before):      298
processes (after):      298
995: Rajiv	Aks	father
processes (before):      298
processes (after):      298
996: Rajiv	Aks	father
processes (before):      298
processes (after):      298
997: Rajiv	Aks	father
processes (before):      298
processes (after):      298
998: Rajiv	Aks	father
processes (before):      298
processes (after):      298
999: Rajiv	Aks	father
```

but I do see some 299s
```bash
processes (before):      298
processes (after):      299
23: Rajiv	Aks	father
....
processes (before):      298
processes (after):      299
49: Rajiv	Aks	father
```

**Comment by RAbraham** [comment]
On Ubuntu Docker.... a few of them are different thought most of them are the same

```bash
processes (before): 8
processes (after): 11
50: Rajiv       Aks     father
processes (before): 8
processes (after): 8
51: Rajiv       Aks     father
processes (before): 8
processes (after): 8
52: Rajiv       Aks     father
processes (before): 8
processes (after): 8
53: Rajiv       Aks     father
processes (before): 8
processes (after): 11
54: Rajiv       Aks     father
```

**Comment by thomasrebele** [comment]
Looks good so far. You wrote the previous loop hangs after executing it twice or three times. Does the loop with the new script run through even if you run it several times?

On September 2, 2019 9:11:18 PM GMT+02:00, Rajiv Abraham <notifications@github.com> wrote:
>On Ubuntu Docker.... a few of them are different thought most of them
>are the same
>
>```bash
>processes (before): 8
>processes (after): 11
>50: Rajiv       Aks     father
>processes (before): 8
>processes (after): 8
>51: Rajiv       Aks     father
>processes (before): 8
>processes (after): 8
>52: Rajiv       Aks     father
>processes (before): 8
>processes (after): 8
>53: Rajiv       Aks     father
>processes (before): 8
>processes (after): 11
>54: Rajiv       Aks     father
>```
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/thomasrebele/bashlog/issues/3#issuecomment-527226754

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by RAbraham** [comment]
that's great to hear. This new script runs several times without hanging :). Just to confirm, I do this.

```bash
rm -rf tmp && rm result_ancestor.txt && mkdir tmp && bash -c 'for ((i=1; i<1000; i++)); do bash ./ancestor.sh | sed "s/^/$i: /"; done' &> result_ancestor.txt
```

where `ancestor.sh` outputs the above. 

Let me know if you think the issue is resolved and I should close this ticket!

**Comment by thomasrebele** [comment]
Great! Thanks a lot for your help. I'll implement the new locking in the following days. Please leave the ticket open. I'll ask you whether the update of bashlog fixed the original problem.

On September 2, 2019 10:26:57 PM GMT+02:00, Rajiv Abraham <notifications@github.com> wrote:
>that's great to hear. This new script runs several times without
>hanging :). Just to confirm, I do this.
>
>```bash
>rm -rf tmp && rm result_ancestor.txt && mkdir tmp && bash -c 'for
>((i=1; i<1000; i++)); do bash ./ancestor.sh | sed "s/^/$i: /"; done' &>
>result_ancestor.txt
>```
>
>where `ancestor.sh` outputs the above. 
>
>Let me know if you think the issue is resolved and I should close this
>ticket!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/thomasrebele/bashlog/issues/3#issuecomment-527238033

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by RAbraham** [comment]
Thank you for the support! This idea of using unix for datalog has galvanized me into relearning datalog. So I look forward to it!

**Comment by thomasrebele** [comment]
I uploaded a new release at https://github.com/thomasrebele/bashlog/releases
The update of the web interface is a bit more involved. I'll hope I'll find some time in the following days.

**Comment by RAbraham** [comment]
Np for me at all. I have moved to using your jar files.
